name: Build and deploy to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Upgrade npm version
        run: npm install -g npm@next-7

      - name: npm install and build - common
        run: |
          npm ci
          npm run build
        working-directory: common

      - name: npm install and build - client
        run: |
          npm ci
          npm run build
        working-directory: client

      - name: npm install and build - server
        #Requires npm 7.1.1+ to run npm ci here
        run: |
          npm ci
          npm run build --if-present
        working-directory: server

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gillius-pointingpoker'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzurePublishProfile }}
          package: server
